package common

const DataSource = "data_source_"
const ClusterId = "cluster"
const InstanceTypesId = "instance_types"
const PoliciesId = "policies"
const NetworkPoliciesId = "network_policies"
const NetworkPortsId = "network_ports"
const PolicyTypesId = "policy_types"
const RegionsId = "regions"
const RolesId = "roles"
const ServiceAccountsId = "service_accounts"
const ServiceRolesId = "service_roles"
const UsersId = "users"
const CloudAccountsId = "cloud_accounts"
const ProviderTypesId = "provider_types"
const TshirtSizeId = "tshirt_size"
const CertificateId = "certificates"
const ObjectStorageId = "object_storages"
